version: '3.8'

services:

  websocket_server:
    build:
      context: ./server  # Ajusta esto al directorio donde tengas el Dockerfile del servidor
      dockerfile: Dockerfile
    image: websocket_server
    container_name: websocket_server_container
    ports:
      - "8080:8080"  # Mapea el puerto para acceso externo
    tty: true
