version: '3.8'

services:

  websocket_server:
    build:
      context: .  # Ajusta esto al directorio donde tengas el Dockerfile del servidor
      dockerfile: Dockerfile
    image: pong_server
    container_name: pong_server_container
    volumes:
      - .:/app
    ports:
      - "8088:8080"  # Mapea el puerto para acceso externo
    tty: true
